#!/usr/bin/php
<?php
/**
 * Line Macro 1.0 - Copyright (c) 2015-2016 Infotoo International Limited - http://www.infotoo.com (MIT License)
 *
 * Last updated: 2016-03-11
 */

/*
 * The MIT license
 *
 * Copyright (C) 2015 Infotoo International Limited
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

if ( count($argv) < 2 )
{
	echo 'line-macro  INPUT_FILE_PATH  [OUTPUT_FILE_PATH]'."\n";
	exit(1);
}

if ( !isset($argv[2]) )
{
	$DEST = fopen('php://stdout','w');
}
elseif ( ($DEST = fopen($argv[2], 'w' )) == false )
{
	echo 'ERROR: ['.$argv[2].'] not writable'."\n";
	exit(1);
}

line_macro( $DEST, $argv[1]);

fclose($DEST);

function line_macro( $DEST, $src )
{
	static $STACK = array();

	if ( !file_exists($src) )
	{
   		echo 'ERROR: '.$src.' not exists'."\n";
		exit(1);
	}
	$src = realpath($src);

	if ( ($f = fopen($src, 'r' )) == false )
	{
   		echo 'ERROR: ['.$src.'] not readable'."\n";
		exit(1);
	}

	#handle infinte loop
	if ( in_array($src,$STACK) )
	{
   		echo 'ERROR: ['.array_pop($STACK).'] imports ['.$src.'] in loop'."\n";
		exit(1);
	}
	$STACK[] = $src;

	$src_folder = dirname($src).'/';
	while ( $buffer = fgets($f) )
	{
		$match = null;
		#syntax:  ~import FILE_PATH ;
		if ( preg_match('/^\s*\~import\s+([^;]+)\s*;/', $buffer, $match) )
		{
			$filename = preg_match('/^("[^"]+"|\'[^\']+\')$/', $match[1] )? substr($match[1],1,-1) : $match[1];
			line_macro( $DEST, $src_folder.$filename );
			continue;
		}
		#no change
		fwrite($DEST, $buffer );
	}
	fclose($f);

	array_pop($STACK);
}

